// CustomTagPipeDirAssignment/src/app/deposit-calculator/deposit-calculator.component.ts
import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'deposit-calculator',
  imports: [FormsModule,CommonModule],
  templateUrl: './deposit-calculator.component.html',
  styleUrl: './deposit-calculator.component.css'
})
export class DepositCalculatorComponent {
  depositAmount:number=0;
  depositTenure:number=0;

  interestRate:number=0.07;
  maturityAmount:number=0;

  calculateDeposit():void{
    if (this.depositTenure >= 10) {
        alert('Please enter valid values. Tenure should be less than or equal to 10 years.');
        return;
    }
    this.maturityAmount = this.depositAmount * Math.pow((1 + this.interestRate), this.depositTenure);
    this.maturityAmount = parseFloat(this.maturityAmount.toFixed(2));
  }
}

<div class="service-page">
<h1>Calculate Deposit</h1>
<hr style="width: 100%;">
<div class="deposit-form">
    <label for="deposit-amount">Deposit Amount:</label>
    <input type="number" id="deposit-amount" [(ngModel)]="depositAmount" required placeholder="Enter deposit amount" />
    <label for="deposit-tenure">Deposit Tenure (years):</label>
    <input type="number" id="deposit-tenure" [(ngModel)]="depositTenure" required placeholder="Enter deposit tenure" />
    <button (click)="calculateDeposit()">Calculate</button>
</div>
<hr style="width: 100%;">
<div id="result">
    <p>Maturity Amount: {{maturityAmount | currency:'INR'}}/-</p>
</div>
</div>

// react-netbanking-assignment/src/DepositCalculator.js
import React from 'react'
import { useState } from 'react'
const DepositCalculator = () => {
    const [depositAmount, setDepositAmount] = useState(0)
    const [tenure, setTenure] = useState(0)
    const [result, setResult] = useState(0)

    const changeDepositAmount=(e)=>{
        setDepositAmount(e.target.value)
    }
    const changeTenure=(e)=>{
        setTenure(e.target.value)
    }
    const calculateDeposit=()=>{
        if(tenure<=0){
            alert("Deposit Tenure must be greater than 0")
            return;
        }
        if(depositAmount<=0){
            alert("Deposit Amount must be greater than 0")
            return;
        }
        const interestRate = 0.07;
        const maturityAmount = depositAmount * Math.pow((1 + interestRate), tenure);
        setResult(maturityAmount)
    }
    return (
    <div className='service'>
        <h1>Calculate Deposit</h1>
        <div class="service-form">
            <label for="deposit-amount">Deposit Amount:</label>
            <input type="number" id="deposit-amount" value={depositAmount} onChange={changeDepositAmount} placeholder="Enter deposit amount" />
            <label for='number'>Interest Rate</label>
            <input disabled value={7}/>
            <label for="deposit-tenure">Deposit Tenure (years):</label>
            <input type="number" id="deposit-tenure" value={tenure} onChange={changeTenure} placeholder="Enter deposit tenure" />
            <button onClick={calculateDeposit}>Calculate</button>
        </div>
        {result!==0?
        <div id="result">
            <p>Maturity Amount: Rs{result.toFixed(2)}/-</p>
        </div>:<></>
        }  
    </div>
    )
}

export default DepositCalculator
