// react-netbanking-assignment/src/LoanCalculator.js
import React from 'react'
import { useState } from 'react'

const LoanCalculator = () => {
    const [name, setName] = useState("Guest")
    const [loanType, setLoanType] = useState({type:'Home',interestRate:9,maxTenure:30,minAmount:500000,maxAmount:10000000})
    const [result, setResult] = useState({emi:0,totalPayment:0,totalInterest:0})
    const [tenure, setTenure] = useState(0)
    const [loanAmount, setLoanAmount] = useState(0)

    const changeLoanType=(e)=>{
        if(e.target.value==='Home'){
            setLoanType({type:'Home',interestRate:9,maxTenure:30,minAmount:500000,maxAmount:10000000})
        }
        else if(e.target.value==='Car'){
            setLoanType({type:'Car',interestRate:11,maxTenure:7,minAmount:100000,maxAmount:1500000})
        }
        else if(e.target.value==='Personal'){
            setLoanType({type:'Personal',interestRate:15,maxTenure:5,minAmount:10000,maxAmount:500000})
        }
    }
    const changeTenure=(e)=>{
        setTenure(e.target.value)
    }
    const changeLoanAmount=(e)=>{
        setLoanAmount(e.target.value)
    }
    const calculateLoan=()=>{
        if(tenure>loanType.maxTenure || tenure<=0){
            alert(`Tenure must be in between 1 and ${loanType.maxTenure}`)
            return;
        }
        if(loanAmount<loanType.minAmount || loanAmount>loanType.maxAmount){
            alert(`Loan Amount must be in range ${loanType.minAmount} to ${loanType.maxAmount}`)
            return;
        }
        const interestRate = loanType.interestRate / 12 / 100;
        const emi = (loanAmount * interestRate * Math.pow(1 + interestRate, tenure * 12)) / (Math.pow(1 + interestRate, tenure * 12) - 1);
        const totalPayment = emi * tenure * 12;
        const totalInterest = totalPayment - loanAmount;

        setResult({
            emi: emi,
            totalPayment: totalPayment,
            totalInterest: totalInterest
        });
    }
    return (
    <div className='service'>
        <h1>Calculate Loan</h1>
        <form class="service-form">
            <label for="applicant-name">Applicant Name:</label>
            <input type="text" id="applicant-name" value={name} placeholder="Enter applicant name" onChange={(e)=>setName(e.target.value)} />
            <label for="loan-type">Loan Type:</label>
            <select id="loan-type" onChange={changeLoanType}>
                <option value="Home">Home Loan</option>
                <option value="Car">Car Loan</option>
                <option value="Personal">Personal Loan</option>
            </select>
            <label for="interest-rate">Interest Rate </label>
            <input type='number' disabled id='interest-rate' value={loanType.interestRate}/>
            <label for="loan-tenure">Loan Tenure (years):</label>
            <input type="number" id="loan-tenure" value={tenure} onChange={changeTenure} placeholder="Enter loan tenure (years)" />
            <label for="loan-amount">Loan Amount:</label>
            <input type="number" id="loan-amount" value={loanAmount} onChange={changeLoanAmount} placeholder="Enter loan amount" />
            <button type='button' onClick={calculateLoan}>Calculate</button>
        </form>
        { result.emi!==0? <div id="result">
            <h2>Hello! {name}</h2>
            <p>Monthly EMI: Rs{result.emi.toFixed(2)}</p>
            <p>Total Payment: Rs{result.totalPayment.toFixed(2)}</p>
            <p>Total Interest: Rs{result.totalInterest.toFixed(2)}</p>
        </div>:<></>
        }
    </div>
    )
}

export default LoanCalculator

// AngularNetBanking/src/app/loan-calculator/loan-calculator.component.ts
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';

type loanTypeDetails={
  type:string,
  interestRate:number,
  maxTenure:number,
  minAmount:number,
  maxAmount:number
}

@Component({
  selector: 'loan-calculator',
  imports: [FormsModule],
  templateUrl: './loan-calculator.component.html',
  styleUrl: './loan-calculator.component.css'
})

export class LoanCalculatorComponent {
  name:string="";
  loanAmount:number=0;
  type:string="Home";
  loanType:loanTypeDetails={type:"Home",interestRate:9,maxTenure:30,minAmount:500000,maxAmount:10000000};
  loanTenure:number=0;

  emi:number=0;
  totalPayment:number=0;
  totalInterest:number=0;

  setLoanType():void{
    if(this.type==="Car"){
      this.loanType={type:"Car",interestRate:11,maxTenure:7,minAmount:100000,maxAmount:1500000};
    }
    else if(this.type==="Personal"){
      this.loanType={type:"Personal",interestRate:15,maxTenure:5,minAmount:10000,maxAmount:500000};
    }
    else{
      this.loanType={type:"Home",interestRate:9,maxTenure:30,minAmount:500000,maxAmount:10000000};
    }
    console.log(this.loanType)
  }

  calculateLoan():void {
    if (this.loanTenure>this.loanType.maxTenure) {
        alert(`Loan tenure exceeds the maximum allowed (${this.loanType.maxTenure} years) for the selected loan type`);
        return;
    }
    if (this.loanAmount<this.loanType.minAmount || this.loanAmount>this.loanType.maxAmount) {
        alert(`Loan amount is out of the allowed range (${this.loanType.minAmount},${this.loanType.minAmount}) for the selected loan type`);
        return;
    }
    if (!this.loanAmount || !this.loanTenure) {
        alert('Please fill all the fields');
        return;
    }
    
    const interestRate = this.loanType.interestRate / 100;
    const tenureInMonths = this.loanTenure * 12;
    const monthlyInterestRate = interestRate / 12;

    this.emi = (this.loanAmount * monthlyInterestRate * Math.pow(1 + monthlyInterestRate, tenureInMonths)) / (Math.pow(1 + monthlyInterestRate, tenureInMonths) - 1);
    this.totalPayment = this.emi * tenureInMonths;
    this.totalInterest = this.totalPayment - this.loanAmount;

    this.emi = parseFloat(this.emi.toFixed(2));
    this.totalPayment = parseFloat(this.totalPayment.toFixed(2));
    this.totalInterest = parseFloat(this.totalInterest.toFixed(2));
  }
}



<div class="service-page">
    <h1>Calculate Loan</h1>
    <hr style="width: 100%;">
    <div class="loan-form">
        <label for="applicant-name">Applicant Name:</label>
        <input type="text" id="applicant-name" pattern="[A-Za-z\s]+" required [(ngModel)]="name" />
        <label for="loan-type">Loan Type:</label>
        <select id="loan-type" [(ngModel)]="type" (change)="setLoanType()">
            <option value="Home">Home Loan</option>
            <option value="Car">Car Loan</option>
            <option value="Personal">Personal Loan</option>
        </select>
        <label for="loan-tenure">Loan Tenure (years):</label>
        <input type="number" id="loan-tenure" [(ngModel)]="loanTenure" required min="0" [max]="loanType.maxTenure" title="Loan Tenure must be in between 0 and {{loanType.maxTenure}}" placeholder="Enter loan tenure (years)" />
        <label for="loan-amount">Loan Amount:</label>
        <input type="number" id="loan-amount" [(ngModel)]="loanAmount" required [min]="loanType.minAmount" [max]="loanType.maxAmount" placeholder="Enter loan amount" title="Loan amount must be in range {{loanType.minAmount}} and {{loanType.maxAmount}}" />
        <button (click)="calculateLoan()">Calculate</button>
    </div>
    <hr style="width: 100%;">
    <div id="result">
        <p>Monthly EMI: Rs{{emi}}</p>
        <p>Total Payment: Rs{{totalPayment}}</p>
        <p>Total Interest: Rs{{totalInterest}}</p>
    </div>
</div>
